language: go
go:
  - 1.3
  - 1.4
install:
  - go get gopkg.in/yaml.v2
  - GOARCH=386 GOOS=linux go build ./minegate
  - GOARCH=amd64 GOOS=linux go build ./minegate
  - GOARCH=386 GOOS=windows go build ./minegate
  - GOARCH=amd64 GOOS=windows go build ./minegate
