language: go
go:
- 1.3
- 1.4
env:
  global:
  - PATH=$PATH:$HOME/gopath/bin
  - CURRENT_COMMIT=$(printf %.8s $TRAVIS_COMMIT)
  - 'BUILD_DATE=$(date "+%a %b %d %Y %T %z")'
branches:
  except:
    - stable
    - release
before_install:
- 'export MINEGATE_VER=${TRAVIS_TAG:-dev@$CURRENT_COMMIT}'
- go get -v github.com/mitchellh/gox
- python plugin.py --gen
- 'python version.py "$MINEGATE_VER" "$MINEGATE_VER commit $(printf %.8s $TRAVIS_COMMIT) build #$TRAVIS_BUILD_NUMBER {{.OS}}/{{.Arch}}"'
- go get -v -t ./build/...
- gox -build-toolchain -os="linux windows" -arch="386 amd64" -verbose 
install:
- "gox -os='linux windows' -arch='386 amd64' -verbose -output='{{.OS}}-{{.Arch}}' ./build"
- cp windows-386.exe $HOME/MineGate-Windows-x86.exe
- cp windows-amd64.exe $HOME/MineGate-Windows-x64.exe
- cp linux-386 $HOME/MineGate-Linux-x86
- cp linux-amd64 $HOME/MineGate-Linux-x64
deploy:
  provider: releases
  api_key:
    secure: VnM05d38bT8E6Yw/FWU0REMyfDzNileFiGIScCAyuXLlBaXBh+2lGe795ercwFpEPP4PdvxUJ4alnOYbuxukaLFerH18L5srb0dZ5Jv6z8MvZAt6djXe95M0tzLOW7NGCP+fjt6hl67OrMl0ZEjLO+C2qUdSS6KyU3voCSCQ60g=
  file:
  - '$HOME/MineGate-Windows-x86.exe'
  - '$HOME/MineGate-Windows-x64.exe'
  - '$HOME/MineGate-Linux-x86'
  - '$HOME/MineGate-Linux-x64'
  skip_cleanup: true
  on:
    go: 1.4
    tags: true
    all_branches: true
