language: go
go:
- 1.3
- 1.4
env:
- PATH=$PATH:$HOME/gopath/bin
before_install:
- go get github.com/jackyyf/gox
#- go get gopkg.in/yaml.v2
#- go get github.com/jackyyf/MineGate-Go/mcchat
#- go get github.com/jackyyf/golog
- go get -v ./minegate/...
- gox -build-toolchain -os="linux windows" -arch="386 amd64"
install:
- "gox -os='linux windows' -arch='386 amd64' -verbose -output='{{.OS}}-{{.Arch}}' -ldflags=\"-X main.version_short 0.3.3 -X main.version_full '0.3.3 commit $(printf %.8f $TRAVIS_COMMIT) build #$TRAVIS_BUILD_NUMBER({{.OS}}/{{.Arch}}) $(date '+%a %b %d %Y %T %z')\" ./minegate"
- mv windows-386.exe $HOME/MineGate-Windows-x86.exe
- mv windows-amd64.exe $HOME/MineGate-Windows-x64.exe
- mv linux-386 $HOME/MineGate-Linux-x86
- mv linux-amd64 $HOME/MineGate-Linux-x64
deploy:
  provider: releases
  api_key:
    secure: VnM05d38bT8E6Yw/FWU0REMyfDzNileFiGIScCAyuXLlBaXBh+2lGe795ercwFpEPP4PdvxUJ4alnOYbuxukaLFerH18L5srb0dZ5Jv6z8MvZAt6djXe95M0tzLOW7NGCP+fjt6hl67OrMl0ZEjLO+C2qUdSS6KyU3voCSCQ60g=
  file:
  - '$HOME/MineGate-Windows-x86.exe'
  - '$HOME/MineGate-Windows-x64.exe'
  - '$HOME/MineGate-Linux-x86'
  - '$HOME/MineGate-Linux-x64'
  skip_cleanup: true
  on:
    go: 1.4
    tags: true
    all_branches: true
